# -*- coding: utf-8 -*-
"""aul18_a_20_pacotes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7oelF86PE9kx_fuh4Ate3rRKZVBhu-P

Aula 18- Pacote Datetime
"""

import datetime

Dia_hoje = datetime.datetime.today()
print(Dia_hoje)

type(Dia_hoje)

print(datetime.datetime.today().date())

Data = datetime.datetime.today().date()

Data_ano = Data.year
Data_dia = Data.day
Data_mes = Data.month

print(Data_dia,Data_mes,Data_ano)

#Cria uma variavel com formato de data
Data_antiga = datetime.date(2025,1,1)

Data - Data_antiga

Data.strftime('%d/%m/%y')

#Somar dia na data de hoje
Data + datetime.timedelta(days=29)

"""Aula 19 - Pacote time"""

import time

print('Comecei agora...')
time.sleep(3)
print('Terminei!!')

Agora = time.localtime()
print(Agora)
print(type(Agora))

time.strftime("%m/%d/%y, %H:%M:%S", Agora)

"""Aula 20- Pacote Math"""

import math

Tupla = (1,2,3,4,6)

#encontra o menor numero
min(Tupla)

# encontra o maior numero
max(Tupla)

# Deixa num negativo em positivo
abs(-9)

#faz uma potenciacao ex- 3 elevado a 4 potencia
pow(3,4)

#Raiz quadrada de um numero
math.sqrt(81)

#Arrendonda um numero para cima = ceil
math.ceil(1.4)

#arrendonda um numero para baixo = floor
math.floor(1.4)

#Numero pi
math.pi



"""Aula 21 - Pacote Random"""

import random

Lista = [0,1,2,3,4,5,6,7,8]

random.choice(Lista)

Palavra = 'Exemplo'
random.choice(Palavra)

random.random()

random.randint(0,100)

Lista_Palavras = ['Matheus','João','Gabriel','Fernando']
random.choice(Lista_Palavras)



"""Aula 22 - Pacote Statistics"""

import statistics

Lista_01 = [12,15,26,56,78,78,80]

sum(Lista_01)/ len(Lista_01)

# Tirando a media da soma dos numeros da lista
statistics.mean(Lista_01)

#Tirando a mediana (Media dos dois valores que estao no centro)
statistics.median(Lista_01)

#Tirando a moda (numero que mais se repete na lista)
statistics.mode(Lista_01)

