# -*- coding: utf-8 -*-
"""Aula31e32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PmMvyoaonixJU4sbX6FCZEFYLl-SU5Cw

Aula 31- Pip install
instalando pacotes que nao estão instalados nativamente
"""

pip install pandas

import pandas

"""Aula 32 - Print Formatado"""

#Print normal
print('Soma de 2 + 2 é', 2 + 2)

#print formatado
print(f'Soma de 2 + 2 é: {2+2}')

#outra forma
print('A soma de 2 + 2 é: {}'.format(2+2))