# -*- coding: utf-8 -*-
"""aula10a17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NdlGyOgM3NLKBaGNgJ3EsSpnvufhWN5U

Aula 10 - Fatiamento de Strings
Strings são listas de bytes representando caracteres
"""

String = "Aprender phyton é Top!"

print(type(String))
print(len(String))

String[0]

String[5]

String[0:8]

String[-1]

String[-5:]



"""Aula 11- Manipulação de string"""

String_01 = 'Hello World!'
print(String_01)

len(String_01)

type(String_01)

String_01 + ' Concatenei!'

#Replace -> Substituir
String_01.replace('Hello World!', 'Olá Mundo!')

CPF = 'CPF:09920202020'
int(CPF.replace('CPF:',''))

#Verificar o comeco
String_01.startswith('Hello')

#Verificar o fim
String_01.endswith('!')

#COntar palavras/letras
String_01.count('l')

# Transformacao
Nome = 'matheus'

Nome.capitalize()

#Verificar se existe
String_cpf = '0939393939'

String_cpf.isdigit()

#Verificar se uma string é alphanumerica

String_01.isalnum()

Nome_02 = 'matheus'
Nome_02.upper()

Nome_03 = 'MATHEUS'
Nome_03.lower()

Frase = 'Hoje o dia está calor!'

Frase.find('H')

Frase.find('frio')

#Remover espaços

Endereco = ' R Luiza 22, PR '
Endereco

Endereco.strip()

#Dividir uma string
Endereco_01 = 'Rua Luiza 22, Sertao,PR'

Endereco_01.split(',')

Endereco_01.split(' ')

"""Aula 12 - COmando Input"""

#input
input('Alguma mensagem')

#Form

Nome_form = input('Qual seu nome: ')
Idade_form = input('Qual sua idade: ')

print('Seu nome é:', Nome_form)
print('Sua idade é:', Idade_form)

"""Aula 13 - Operadores de comparacao"""

10 == 10

10 == 8

10 != 12

10 != 10

10 > 2

10 >= 10

10 < 9

10 <= 10



"""Aula 14 - Operadoreslogicos"""

#And
10 > 3 and 10 > 5

#or
10 > 20 or 10 > 100

Lista_01 = [1,2,3,4]

#verificar se um numero esta em uma lista

20 not in Lista_01

1 in Lista_01

"""Aula 15 - operadores de identidade"""

#is e isnot
str_01 = 'Ola Mundo'
str_02 = 'Ola Mundo'

type(str_01) is type(str_02)

type(str_01) is not type(str_02)



"""Aula 16-Operadores de Associação

"""

Lista_acoes = ['Magalu','Via','Carrefour']

'Via' in Lista_acoes

'Apple'in Lista_acoes



"""Aula 17 - Manipulando Listas"""

Lista_nova = []

#Append
Lista_nova.append(1)
Lista_nova.append(2)
Lista_nova.append(3)
Lista_nova.append('Valor')

Lista_nova

len(Lista_nova)

#clear - limpar a lista
print(Lista_nova)
Lista_nova.clear()
print(Lista_nova)

#insert - inserir na lista podendo escolher a posição
Lista_nova
Lista_nova.insert(0,0)
Lista_nova

Lista_nova.insert(2,1.5)
Lista_nova

#extend - junta duas listas
l_um = [1,2,3,4,5]
l_dois = [6,7,8,9,10]
l_um.extend(l_dois)
l_um

# remove - remove item da lista
l_um.remove(1)
l_um

#pop - remove item pelo seu indice
l_um.pop(0)

l_um

#sort - ordena a lista
alfabeto = ['w','e','t','y','u','i','j']
alfabeto
alfabeto.sort()
alfabeto

#copy - faz uma copia de uma lista em outra
l_tres = l_um.copy()

l_tres

#encotrar o indice de um item
l_tres.index(3)

