# -*- coding: utf-8 -*-
"""aula23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Li3J6T5k7h_WHmp8ihsvZfWaZtqWJOu

Aula 23- Condição IF
"""

#COndicao se a pessoa tiver menos de 18 anos , ela nao entra no sistema
Idade = 23

if Idade >= 18:
  print('Você é maior de idade')

if Idade >= 18:
  print('Você é maior de idade')
else:
  print('Você é menor de idade')

if Idade >= 18:
  print('Você é maior de idade')

elif Idade < 18 and Idade >= 15:
  print('Você pode entrar com um responsavel')
else:
  print('Você é menor de idade')



"""Aula 24 - Laço FOr"""

for QualquerCoisa in range(10):
  print(QualquerCoisa )

for QualquerCoisa in range(1,10):
  print(QualquerCoisa )

Lista_paises =['Brasil','Argentina','Paraguai','Colombia','Chile','Equador','Uruguai']

for ListarPaises in Lista_paises:
  print(ListarPaises.upper()[0:3])

for Pais in Lista_paises:
  if Pais == 'Uruguai':
    print(Pais, 'é BICAMPEÃO Mundial')
  elif Pais == 'Brasil':
    print(Pais, 'é PENTACAMPEÃO Mundial')
  elif Pais == 'Argentina':
    print(Pais, 'é TRICAMPEÃO Mundial')
  else :
    print(Pais, ' não é campeão Mundial')

for Loop in range(0, len(Lista_paises)):
  print(Lista_paises[Loop])

for Index , Pais in enumerate(Lista_paises):
  print(Index, Pais)

x = 0

for Pais in Lista_paises:
  print(x, Pais)
  x+=1

Lista_Num = [Numero for Numero in range(0,10)]
Lista_Num
#Pode ser feito operações tbm
Lista_Op = [Num ** 2 for Num in range(0,10)]
Lista_Op

#outra forma de fazer
Lista_NumDois = []

for Loop in range(0,10):
  Lista_NumDois.append( Loop )

Lista_NumDois

