# -*- coding: utf-8 -*-
"""Aula27_ao_30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H3DTQCQv7skSPmhwjzrDWKKuA5PZx5Hz

AUla 27 - Estrutura de funções
"""

def Boas_Vindas():
  print('++++++Python++++++')

Boas_Vindas()

#funcao para somar numeros
def Somar(v1,v2):
  Soma = v1 + v2
  print(Soma)

Somar(90,90)

for Loop in range (0,10):
  import random

  x = random.random()
  y = random.random()
  Somar(x,y)

"""Aula 28 - Função Lambda
-É uma pequena função anonima
-Pode receber qualquer numero dde argumentos, mas apenas uma expressão
"""

Funcao_soma = lambda valor_1 : valor_1 + 10

Funcao_soma(10)

Funcao_soma_02 = lambda valor_1 , valor_2 : valor_1 + valor_2

Funcao_soma_02(29,39)

#Lambda com if

Exemplo = lambda valor : 'Verdadeiro' if valor % 2 == 0 else 'Falso'

Exemplo(2245)

"""Aula 29 - Try
Funciona para mitigar possiveis erros no codigo
"""

try:
  # 0/0
  print('Codigo aceito')
except:
  print('Erro Encontrado')

try:
  teste = 5 == 6
  print(teste)
except:
  print('codigo errado')

"""aula 30 - Classes"""

class Pessoa:
  #Metodo Construtor
  def __init__(self,Nome,Idade):
    self.Nome = Nome
    self.Idade = Idade
  def Bem_vindo(self):
    print('Usuario cadastrado,Seja bem vindo', self.Nome)

  def Recusado(self):
    print('Usuario recusado')

  #Funcao
  def Maior_idade(self):
    if self.Idade >=18 :
      print('Usuario maior de idade')
      self.Bem_vindo()
    else :
      print('Usuario menor de idade')
      self.Recusado()

Dados = Pessoa('Matheus',26)

Dados.Maior_idade()

