# -*- coding: utf-8 -*-
"""Aula3_4_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A4utNIljzDgKcT7ZD60sWDq2y8JK2bIZ
"""



"""Aula 03 - Phyton para Analise de dados"""

print("Bem vindo ao curso de Phyton")

# Comentario!!

'''
  Comentario
  Comentario
'''

print("Ola mundo \n teste ")



"""Aula 04 - Operadores Matemáticos"""

# soma
4 + 4

# subtração
4-0

# multiplicacao
4*4

# Divisão
4/4

# exponenciacao
2 ** 3

# resto da divisao
3 % 4

# Divisao de chao
3 // 4



"""Aula 5 - variaveis

"""

# Variaveis de Texto
Var_texto_um = 'Teste 01 -'
Var_texto_dois = str('Teste 02')
print(Var_texto_um, Var_texto_dois)

# Variaveis Numericas
Var_num_01 = 100
Var_num_02 = int(200)
print(Var_num_01, Var_num_02)

#Var Flutuantes
Var_float_01 = 10.00
Var_float_02 = float(10.50)

print(Var_float_01, Var_float_02)

#Var boleanas
Var_booleano_01 = True
Var_booleano_02 = False

print(Var_booleano_01,Var_booleano_02)

