# -*- coding: utf-8 -*-
"""Case_Games.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZkjLfS9CxpC0aHCjt5rdTUgofBM1PuD
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

import warnings
warnings.filterwarnings('ignore')

Base_Dados = pd.read_csv('PS4_GamesSales.csv', encoding='latin-1')

Base_Dados.head()

Base_Dados.shape

Base_Dados.isnull().sum()

plt.figure(figsize=(14,5))
plt.title('Verificando campos nulos')
sns.heatmap(Base_Dados.isnull(),cbar=False);

# retirando valores nulos
Base_Dados.dropna( inplace=True)

Base_Dados.describe(

)

plt.figure(figsize=(10,5))
plt.title('Quantidade de Vendas Globais (mi)',loc='left',fontsize=14)
sns.barplot(data=Base_Dados,x='Year',y='Global',ci=None, color='#69b3a2', estimator=sum)
plt.ylabel('Quantidade Vendas (mi)');

Base_Dados = Base_Dados.loc[(Base_Dados['Year'] != 2019) & (Base_Dados['Year'] != 2020)]
Base_Dados.head()

#tamanho
plt.figure(figsize=(12,5))

#estilo
plt.style.use('ggplot')

#titulo
plt.title('Distribuição das vendas Globais',loc='left', fontsize=14)

#plot

sns.kdeplot( Base_Dados['Global'], shade=True, bw=1 , color='#96a8a8', linewidth=2.5);

print(plt.style.available)

plt.title('Análise da distribuição Global(mi)')

sns.boxplot(data=Base_Dados,x='Year',y='Global')

Base_Dados.loc[Base_Dados['Global']>=10]

SportsData = Base_Dados.loc[Base_Dados['Genre'] == 'Sports']
SportsData.head()

Analise = Base_Dados.groupby( by=['Year'] ).sum().reset_index()

Analise.dropna( inplace=True )

AmericaNorte = [(AmericaNorte / Total) * 100 if Total != 0 else 0 for AmericaNorte,Total in zip(Analise['North America'],Analise['Global'])]
Europa = [(Europa / Total) * 100 if Total != 0 else 0 for Europa,Total in zip(Analise['Europe'],Analise['Global'])]
Japao = [(Japao / Total) * 100 if Total != 0 else 0 for Japao,Total in zip(Analise['Japan'],Analise['Global'])]
RestoDoMundo = [(RestoDoMundo / Total) * 100 if Total != 0 else 0 for RestoDoMundo,Total in zip(Analise['Rest of World'],Analise['Global'])]

#Tamanho
plt.figure(figsize=(10,5))

Largura_barra = 0.85
Rotulos = Analise['Year']
Grupos = [0,1,2,3,4,5]
plt.title('Análise distribuição por continentes')

#plot america
plt.bar(Grupos, AmericaNorte, width=Largura_barra, color='#b5ffb9', edgecolor='white')

#plot europa
plt.bar(Grupos,Europa,width=Largura_barra,bottom=AmericaNorte,color='#f9bc86',edgecolor='white')


#plot Japao
plt.bar(Grupos,Japao,width=Largura_barra,bottom=[ A + B for A, B in zip(AmericaNorte, Europa) ],color='#a3acff',edgecolor='white')


#plot resto do mundo
plt.bar(Grupos,Japao,width=Largura_barra,bottom=[ A + B + C for A, B , C in zip(AmericaNorte, Europa,Japao) ],color='#d3acfe',edgecolor='white')


# Labels
plt.xticks( Grupos, Rotulos )
plt.xlabel('Grupo')
plt.ylabel('Distribuição %')

# Legenda
plt.legend( ['America N', 'Europa',' Japão', 'Mundo'], loc='upper left', bbox_to_anchor=(0.15, -0.1), ncol=4 );

Base_Dados['Publisher'].unique()

#Substituição do valor de texto para numerico
from sklearn.preprocessing import LabelEncoder
Funcao_Label = LabelEncoder()

Base_Dados['Produtor'] = Funcao_Label.fit_transform( Base_Dados['Publisher'])
Base_Dados['Genero'] = Funcao_Label.fit_transform( Base_Dados['Genre'])
Base_Dados['Jogo'] = Funcao_Label.fit_transform( Base_Dados['Game'])

Base_Dados.head()

Paleta_Cores = sns.color_palette('husl',8)
Paleta_Cores

plt.figure(figsize=(12,5))
plt.title('Análise dos produtores de Games(mi)')
sns.scatterplot(data=Base_Dados,x='Produtor',y='Global', color=Paleta_Cores[0])

plt.figure(figsize=(12,5))
plt.title('Análise dos Generos de Games(mi)')
sns.scatterplot(data=Base_Dados,x='Genero',y='Global', color=Paleta_Cores[0])

plt.figure(figsize=(12,5))
plt.title('Análise das Vendas de Games(mi)')
sns.scatterplot(data=Base_Dados,x='Jogo',y='Global', color=Paleta_Cores[0])

Base_Dados.query("Publisher == 'Rockstar Games'")

Base_Dados.query("`North America` > 4")

Base_Dados.query("`Europe` > 4")

Base_Dados.query("`Japan` > 0.5")

Base_Dados.query("`Rest of World` > 2")

#Relatorio --> report para o Chefe

fig, ax = plt.subplots( figsize=(18,15))

#Cor de fundo
Cor_Fundo = '#f5f5f5'
ax.set_facecolor( Cor_Fundo)
fig.set_facecolor( Cor_Fundo)

#Estilo dos graficos
plt.style.use('seaborn-v0_8')
plt.suptitle('Python para Análise de Dados \n Projeto pratico 5 - Análise Mercado de Games PS4', fontsize=22, color='#404040',fontweight=600)
#Parametros para o grid
Linhas = 3
Colunas = 2

#Acessando Grafico 1
plt.subplot(Linhas,Colunas, 1)
#titulo
plt.title(' Quantidade de vendas Globais(mi)',loc='left',fontsize=14)
#Grafico
plt.bar(Base_Dados['Year'], Base_Dados['Global'],color='#69b3a2')


#Acessando Grafico 2
plt.subplot(Linhas,Colunas, 2)
plt.title('Analise da distribuição Global (mi)')
#grafico
sns.boxplot(data=Base_Dados, x='Year',y='Global')


# Acessando Grafico 3
plt.subplot(Linhas,Colunas, 3)

Largura_barra = 0.85
Rotulos = Analise['Year']
Grupos = [0,1,2,3,4,5]
plt.title('Análise distribuição por continentes', loc='left', fontsize=14)

#plot america
plt.bar(Grupos, AmericaNorte, width=Largura_barra, color='#b5ffb9', edgecolor='white')
#plot europa
plt.bar(Grupos,Europa,width=Largura_barra,bottom=AmericaNorte,color='#f9bc86',edgecolor='white')
#plot Japao
plt.bar(Grupos,Japao,width=Largura_barra,bottom=[ A + B for A, B in zip(AmericaNorte, Europa) ],color='#a3acff',edgecolor='white')
#plot resto do mundo
plt.bar(Grupos,Japao,width=Largura_barra,bottom=[ A + B + C for A, B , C in zip(AmericaNorte, Europa,Japao) ],color='#d3acfe',edgecolor='white')

# Labels
plt.xticks( Grupos, Rotulos )
plt.xlabel('Grupo')
plt.ylabel('Distribuição %')

# Legenda
plt.legend( ['America N', 'Europa',' Japão', 'Mundo'], loc='upper left', bbox_to_anchor=(0.15, -0.1), ncol=4 );

#Acessando o Grafico 4
plt.subplot(Linhas,Colunas, 4)
plt.title('Analise dos produtores de Game(mi)',loc='left',fontsize=14)
sns.scatterplot(data=Base_Dados,x='Produtor',y='Global',color=Paleta_Cores[0]);

#Acessando o Grafico 5
plt.subplot(Linhas,Colunas, 5)
plt.title('Analise dos generos de Game(mi)',loc='left',fontsize=14)
sns.scatterplot(data=Base_Dados,x='Genero',y='Global',color=Paleta_Cores[0]);

#Grafico 6
plt.subplot(Linhas,Colunas, 6)
plt.title('Analise dos Games(mi)',loc='left',fontsize=14)
sns.scatterplot(data=Base_Dados,x='Jogo',y='Global',color=Paleta_Cores[0]);

#AJustar o layout
plt.subplots_adjust(hspace=0.35, wspace=0.15)

Rodape= '''
  Esse relatório foi elaborado no treinamento d "Python para Análise de Dados"
  Está disponível no canal do youtube @Data Viking
  by: Matheus Mendes
'''

fig.text(0.5,-0.05,Rodape,ha='center',va='bottom',size=12, color='#938ca1')

