# -*- coding: utf-8 -*-
"""Case_Educacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T_Nw1laoUtcluZwqEzyGcOi46gJRRydM
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

Base_Dados = pd.read_csv('StudentsPerformance.csv')

Base_Dados.shape

Base_Dados.head()

#Campos nulos

Nulos = Base_Dados.isnull()

plt.figure(figsize=(16,5))
plt.title('Analise de campos nulos')
sns.heatmap( Nulos, cbar=False);

#Unicos
Base_Dados.nunique()

#Campos duplicados
Base_Dados.duplicated().sum()

#Estatistica

Base_Dados.describe()

#info

Base_Dados.info()

Base_Dados['gender'].value_counts( normalize=True) * 100

Base_Dados['race/ethnicity'].value_counts( normalize=True) * 100

Base_Dados['parental level of education'].value_counts( normalize=True) * 100

Base_Dados['lunch'].value_counts( normalize=True) * 100

Base_Dados['test preparation course'].value_counts( normalize=True) * 100

sns.boxplot(data=Base_Dados, x='math score', y='gender');

sns.boxplot(data=Base_Dados, x='reading score', y='gender');

sns.boxplot(data=Base_Dados, x='writing score', y='gender');

#comparando as notas de matemática por genero
Base_Dados.groupby(by=['gender']).describe()['math score'].reset_index()

sns.pairplot(Base_Dados , hue='race/ethnicity')

sns.boxplot( data=Base_Dados, x='math score', y='race/ethnicity')

sns.boxplot( data=Base_Dados, x='math score', y='parental level of education')

Base_Dados.groupby(by=['parental level of education']).describe()['math score'].reset_index()

sns.boxplot( data=Base_Dados, x='math score', y='test preparation course')

Base_Dados.groupby(by=['test preparation course']).describe()['math score'].reset_index()

sns.scatterplot(data=Base_Dados, x='math score', y='writing score')

