# -*- coding: utf-8 -*-
"""Case_rh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ryBPP3anZpllBZkAQeynuYfQBN-jr4bV
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

Base_Dados = pd.read_csv('Salary_Data.csv')

Base_Dados.head()

Base_Dados.rename(
    columns={
       'YearsExperience' : 'Xp',
       'Salary':'Renda'
     }, inplace=True)

#dimensao
Base_Dados.shape

Base_Dados.isnull().sum()

#Grafico Nulos
sns.heatmap( Base_Dados.isnull(), cbar=False);

Base_Dados.describe()

plt.figure(figsize=(10,6))
plt.title('Análise da Renda')
sns.kdeplot(Base_Dados['Renda'], color='green')

plt.figure(figsize=(10,6))
plt.title('Análise da Xp')
sns.kdeplot(Base_Dados['Xp'], color='green')

# Distribuição
plt.figure( figsize=(10, 5) )
sns.boxplot( Base_Dados['Xp'] );

plt.figure(figsize=(10,5))
sns.scatterplot(data=Base_Dados, x='Renda', y='Xp')

plt.figure(figsize=(10,5))
sns.regplot(data=Base_Dados, x='Renda', y='Xp')

# Correlação
Correlacao = Base_Dados.corr('pearson')
plt.figure( figsize=(10, 5) )
sns.heatmap( Correlacao, annot=True, cbar=True );

# Correlação
Correlacao = Base_Dados.corr('spearman')
plt.figure( figsize=(10, 5) )
sns.heatmap( Correlacao, annot=True, cbar=True );