# -*- coding: utf-8 -*-
"""Case_Financeiro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmjHgyVJwhXaJrleCYpUUN3rzU78x-8V
"""

#Import para modelagens e matrizes
import numpy as np
import pandas as pd

#Import para analises gráficas
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.graph_objects as go

#import para ignorar avisos
import warnings

# Desabilitando avisos
warnings.filterwarnings('ignore')

Base_Dados = pd.read_excel('Vase_004 - Magalu.xlsx')

Base_Dados.head()

Base_Dados.shape

Base_Dados.info()

Base_Dados.describe()

Dados = Base_Dados.set_index('Data')

Dados.head()

plt.style.use('seaborn-v0_8-darkgrid')
plt.figure(figsize=(16,5))
plt.title('Analise das ações da magalu Fechamento', fontsize=14,loc='left')
plt.plot( Dados.index, Dados['Fechamento']);
plt.xlabel('Período da Cotação')
plt.ylabel('Valor da Ação (R$)')

print(plt.style.available)

Dados.tail()

Media_Movel = Dados['Fechamento'].rolling(5).mean()
Media_Tendencia = Dados['Fechamento'].rolling(30).mean()

plt.style.use('seaborn-v0_8-darkgrid')
plt.figure(figsize=(16,5))
plt.title('Analise das ações da magulu - Fechamento', fontsize=15,loc='left')

plt.plot(Dados.index, Dados['Fechamento'])
plt.plot(Dados.index, Media_Movel)
plt.plot(Dados.index, Media_Tendencia)

plt.xlabel('Período da Cotação')
plt.ylabel('Valor da Ação (R$)')

sns.boxplot(data=Dados, x='Fechamento')

Base_Dados['Mes'] = Base_Dados['Data'].dt.month
plt.figure(figsize=(16,5))
sns.boxplot(data=Base_Dados,x='Mes',y='Fechamento')

Base_Dados.groupby(['Mes']).describe()['Fechamento']

Grafico = go.Figure(
    data=[
        go.Candlestick(
            x=Dados.index,
            open=Dados['Abertura'],
            high=Dados['Maior'],
            low=Dados['Menor'],
            close=Dados['Fechamento'],

        )
    ]
)

Grafico.show()

