# -*- coding: utf-8 -*-
"""Case_Unicornios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ot5opfcNgrdevUFYp7qNeCkq2KkN78G4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

Base_Dados = pd.read_csv('unicorns till sep 2022.csv')

Base_Dados

#Renomar
Base_Dados.rename(
    columns={
        'Unnamed: 0': 'id',
        'Company':'Empresa',
        'Valuation ($B)':'Valor ($)',
        'Date Joined': 'Data de Adesão',
        'Country':'País',
        'City':'Cidade',
        'Industry':'Setor',
        'Investors':'Investidores'
    }, inplace=True)

Base_Dados.info()

Base_Dados.isnull().sum()

#grafica
plt.figure(figsize=(15,6))
plt.title('Analisando campos nulos')
sns.heatmap(Base_Dados.isnull(),cbar=False);

#campos unicos
Base_Dados.nunique()

#Valores Unicos
Base_Dados['Setor'].unique()

Base_Dados['Setor'].value_counts()

Base_Dados['Setor'].value_counts( normalize = True)

plt.figure(figsize=(15,6))
plt.title('Analise dos Setores')
plt.bar(Base_Dados['Setor'].value_counts().index, Base_Dados['Setor'].value_counts())
plt.xticks(rotation=45,ha='right')

Analise = round(Base_Dados['País'].value_counts(normalize=True)*100,1)

#Analise Geral
plt.figure(figsize=(15,6))
plt.title('Analise dos Países')
plt.pie(
    Analise,
    labels= Analise.index,
    shadow=True,
    startangle=50,
    autopct='%1.1f%%'
);

#Analise top 10
plt.figure(figsize=(15,6))
plt.title('Analise dos Países')
plt.pie(
    Analise.head(10),
    labels= Analise.index[0:10],
    shadow=True,
    startangle=50,
    autopct='%1.1f%%'
);

#Convertendo as datas de obj para datetime
Base_Dados['Data de Adesão'] = pd.to_datetime( Base_Dados['Data de Adesão'])

Base_Dados['Data de Adesão'].head()

Base_Dados['Mes'] = pd.DatetimeIndex( Base_Dados['Data de Adesão']).month

Base_Dados['Ano'] = pd.DatetimeIndex( Base_Dados['Data de Adesão']).year

Base_Dados.head()

Analise_Agrupada = Base_Dados.groupby(by=['País','Ano','Mes','Empresa']).count().reset_index()
Analise_Agrupada

Analise_Agrupada.loc[
    Analise_Agrupada['País'] == 'Brazil'
]

# Transformando a coluna Valor
Base_Dados['Valor ($)'] = pd.to_numeric( Base_Dados['Valor ($)'].apply( lambda Linha: Linha.replace('$', '') ) )

Base_Dados.head()

#Tabela Analitica de valuation
Analise_Pais = Base_Dados.groupby(by=['País']).agg({'Valor ($)': 'sum'}).reset_index()

Analise_Pais.head()

Analise_valor = Analise_Pais.sort_values('Valor ($)', ascending=False)
Analise_valor.head()

plt.figure( figsize=(15,6) )
plt.plot( Analise_valor['País'], Analise_valor['Valor ($)'] )
plt.title('Analise do Valor por Pais')
plt.xticks( rotation=45, ha='right');