# -*- coding: utf-8 -*-
"""aula33_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUXdyH-QX8I99Tjnj7PHtDxfG3CjOZO-

AUla 33 -Pandas
"""

import pandas as pd
import numpy as np

df = pd.read_csv('timecerto.csv')

type(df)

df.head()

df.tail()

df.columns

#verificar se há linhas duplicadas
df.duplicated().sum

df.info()

#verificar existencia de NaN
df.isna().sum()

#sumario estatistico
df.describe(include = 'all')

#quantidade de valores unicos em cada coluna
df.nunique()

#valores unicos
df['Nome'].unique()

#value_counts - conta a frequencia entre valores
#df.gender.value_counts() --> conta a frequencia entre masc e fem por ex
df.Idade.value_counts()

stats = ['Gls','Ast']
df['Ast'] = pd.to_numeric(df['Ast'], errors='coerce')

df.sort_values(['Gls']).reset_index(drop = True)

df = df.sort_values(by = stats,ascending= False)\
.reset_index(drop = True)

df

# coluna com media
#ele nao da certo aqui pq tem os numeros  em () nos jogos ai n tem a medi
df['mean'] = df[stats].mean(axis = 1)

df.head()

df['Gls'] = pd.to_numeric(df['Gls'], errors='coerce')

df.query('(Gls > 5)')

#Exemplo de query para fazer em uma tabela com notas de alunos
#df[(df.gender == 'male') & (df['test preparition course']== 'none') & (df['math score']>=70 )]

# agrupamento - agrupa os dados por genero e obtem estaticas descritivas
#df.groupby(by = 'gender')[provas].agg([np.mean, np.median]).T