# -*- coding: utf-8 -*-
"""Aula43e44.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VbNi0XVrG64W5H9Z5FBcuicr9LpPmSp

Aula 43 - Numpy

Fornece uma grande conjunto de funções e operações de bibliotece que ajudam programadores a executar facilmente calculos numericos
"""

import numpy as np

print(np.__version__)

#Criar uma matriz
Array = np.array([10,20,30,40,50])

Array

#TIpo
type(Array)

Duas = np.array(
    [
        [10,9,8,7,6],
        [5,4,3,2,1]
    ]
)

print(Duas)

Tres = np.array(
    [
        [15,14,13,12,11],
        [10,9,8,7,6],
        [5,4,3,2,1]
    ]
)

print(Tres)

#Acessar os arrays
# 1ºPosição

Array[0]

#Ultima
Array[-1]

#Range

Array[2:]

#operaçoes
print(Array[0],Array[1])
Array[0] + Array[1]

#Subtração
Array[0] - Array[1]

# Operadoes Logicas
Array[0] == Array[1]

# Verifiicar Dimensoa
Array.shape

Duas.shape

#loop

for Loop in Array:
  print(Loop)

for Loop in Duas:
  print(Loop)

for Loop in Duas:
  for interno in Loop:
    print(interno)

for Loop in Tres:
  for interno in Loop:
      print(interno)

