# -*- coding: utf-8 -*-
"""Aula25e26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oid4JuNsx3AsTc9MvGh-TQZWc1TLFPzF

Aula 25 - While
"""

Parar = 0

while Parar <= 10:
  print(Parar)
  Parar +=1

Loop = 0

while Loop <= 10:
  print(Loop)

  if Loop == 5:
    for x in range(10):
      print(x)
  Loop += 1

#Joguinho
import random
while True:

  Eu = random.randint(0,3)
  Voce = random.randint(2,10)
  print('Eu tirei', Eu)
  print('Voce tirou', Voce)
  if Eu > Voce :
    print('Ganhei!!!')
    break

  print('\n')

"""Aula 26 - Break e COntinue"""

Frutas = ['Morango','Maça','Uva','Abacaxi']

for Fruta in Frutas:
  print(Fruta)
  if Fruta == 'Uva':
    break

#Continue ignora a iteração e nao mostra a informacao
for Num in range(0,11):
  if Num == 5:
    continue
    print('Ignore esse numero')

  print(Num)

