# -*- coding: utf-8 -*-
"""Aula5_ate_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kjn4pPpjs91AnWM64uStVIWcEr7cFHUt
"""



"""Aula 05 - Tipo de dados
1-Listas - São Criadas usando [ ] (Colchetes)
2-Tuplas- São criadas usando ( ) (parenteses)
3-Dicionarios- Sao criadas usando { } (chaves)

---


"""

# Listas
Lista_01 = [1,2,3,4,5,6,7,8]
Lista_02 = ['Nome','Sobrenome','Idade']
Lista_03 = [1,'Texto', True , [1,2,3,4]]

Lista_03

# Tuplas -> São imutaveis!!!!
Tupla_1 = (1,2,3,4,5)
Tupla_2 = ("Texto", 1 , 2.9)

Tupla_1 , Tupla_2

# Dicionario
Dicionario = {
    'Index' : 'Valor',
    'Id' : 1 ,
    'Id' : 2 ,
    'Nome' : 'Odemir',
    'Lista' : Lista_01,
    'Tupla' : Tupla_2
}
Dicionario



"""Aula 06 - Nomeação de variaveis
podemos nomear variaveis e tipos de dados de diversas formas

1.Declarar as variaves em uma unica linha de comando
2.Atribuir um valor a diversas variaveis
3.Declarar usandndo uma lista
4.Combinar variaveis
5..Operar com operadores matematicos
6.Muitos outros
"""

#Nomeando
Laranja,Melao, Limao = 1,2,3
print(Laranja, Melao, Limao)

#Nomeando
Morango = Uva = kiwi ='frutas'
print(Morango,Uva,kiwi)

# Nomear com Listas
Lista_Carros = ['VW', 'Audi','Tesla']
Marca_01, Marca_02, Marca_03 = Lista_Carros
print(Marca_01,Marca_02,Marca_03)

# Combinar variaveis

Nome = 'João'
Sobrenome = 'Frango'

Nome_Completo = Nome + ' ' + Sobrenome
print(Nome_Completo)

"""Aula 07 - Tipo de Informação

1 TExt type : str
2 Numeric Types : int,float,complex
3 Sequence Types: list,tuple , range
4 mapping Type: dict,
5 Set Types: set , frozenset
6 Boolean Type: bool
7Binary types: bytes , bytearray, memoryview
"""

String = str('Ola Mundo')
Inteiro = int(10)
Flutuante = float(100.5)
Complex = complex( 1j )
Lista = list( ('Maça','Morango') )
Tupla = tuple( ('A','B','C'))
Range = range(6)
Dicionario = dict(nome='Odemir',age=29)
Set = set(('A','B','C'))
Boleano = bool( 5 )
Bytes = bytes(5)
ByteArray = bytearray(5)
Memoryview = memoryview( bytes(5))

from datetime import datetime
Data = datetime.today().date()

type (Data)

"""Aula 08 - Comando Round"""

Valor_teste = 10.9299292

round(Valor_teste,2)

"""Aula 09- Comando Len"""

Lista = [1,2,3,4,5,6,7,8]
Dic = {'Nome':'Teste', 'Idade':29}
Tup = (1,2,3)
String = 'Ola Mundo'

len(String)

