# -*- coding: utf-8 -*-
"""aula36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VkCH6hcc8sTmhFd6RZSTNd5XWKlRryo2

Aula 36- Introdução ao Seaborn
"""

import numpy as np
import pandas as pd
import seaborn as sns

#Definir thema
sns.set_theme(style='darkgrid')

#Dados
Base_Dados = sns.load_dataset('tips')

#verificar base
Base_Dados.head()

Base_Dados.rename(columns={
    'total_bill':'Total_conta',
    'tip':'gorjeta',
    'sex':'sexo',
    'smoker':'fumante',
    'day':'dia',
    'time': 'Periodo',
    'size': 'Pessoas_na_mesa'
}, inplace=True)

Base_Dados.head()

"""Aula 37 - Seaborn"""

sns.relplot( x='Total_conta', y= 'gorjeta', data=Base_Dados);

sns.relplot( x='Total_conta', y= 'gorjeta', data=Base_Dados, hue='sexo');

sns.relplot( x='Total_conta', y= 'gorjeta', data=Base_Dados, kind='line');

sns.relplot( x='Total_conta', y= 'gorjeta', data=Base_Dados, kind='line' ,hue='fumante');

"""Grafico histplot

"""

sns.histplot( data= Base_Dados, x='Total_conta' )

sns.histplot( data= Base_Dados, x='Total_conta' , hue='fumante')

"""Grafico barplot

"""

sns.barplot(data=Base_Dados,x='sexo',y='Total_conta',hue='fumante')



"""Grafico pairplot"""

sns.pairplot(Base_Dados)

sns.pairplot(Base_Dados, hue='sexo')



"""Grafico boxplot"""

sns.boxplot(data=Base_Dados, x = 'dia', y='Total_conta');

sns.boxplot(data=Base_Dados, x = 'dia', y='Total_conta',hue='sexo');

